/* =====================================================================
   ⭐  THE WISHLIST — ROOMS YOU WANT TO PLAY
   =====================================================================
   Source: exported from your Morty wishlist (@Poltergeist) via three HAR
   captures over time. 147 → 189 → 197 rooms as your wishlist has grown.
   Morty's own "wishlisted" count on your profile has been stale every
   time; trust this file's count over that badge.

   GEOCODING STATUS: All 197 rooms have real coordinates.
   Give Claude a fresh HAR export any time to pick up new wishlist adds —
   it will automatically diff against this file, geocode only genuinely
   new venues, and reuse coordinates for any repeat venues.

   FIELD REFERENCE: (same shape as ../js/data.js, minus play-specific fields)
     name       (string, required)  — Room name
     venue      (string, required)  — Company / business name
     city       (string)            — City name
     state      (string)            — US state abbreviation e.g. "CA"
     country    (string, required)  — Full country name
     lat/lng    (number, required)  — Coordinates
     score      (number)            — Morty community rating count
     url        (string)            — Morty attraction page
     notes      (string)            — Optional personal notes
===================================================================== */
const WISHLIST = [
  {
    id: "w117",
    name: "Irvine School Of Wizardry And The Dragon Wand",
    venue: "Hidden Donkey",
    city: "Irvine",
    state: "CA",
    country: "United States",
    lat: 33.6912107, lng: -117.8619224,
    url: "https://morty.app/attraction/117/irvine-school-of-wizardry-and-the-dragon-wand",
    notes: "",
  },
  {
    id: "w121",
    name: "Escape the Darkest Hour: Torture Chamber",
    venue: "Mission Escape Games",
    city: "New York",
    state: "NY",
    country: "United States",
    lat: 40.7542064, lng: -73.9916615,
    url: "https://morty.app/attraction/121/escape-the-darkest-hour-torture-chamber",
    notes: "",
  },
  {
    id: "w122",
    name: "Mission's Breakout: The Ultimate Bank Heist",
    venue: "Mission Escape Games",
    city: "New York",
    state: "NY",
    country: "United States",
    lat: 40.7542064, lng: -73.9916615,
    url: "https://morty.app/attraction/122/missions-breakout-the-ultimate-bank-heist",
    notes: "",
  },
  {
    id: "w131",
    name: "The Silence 1",
    venue: "13th Room",
    city: "Pomona",
    state: "CA",
    country: "United States",
    lat: 34.0571687, lng: -117.7497801,
    url: "https://morty.app/attraction/131/the-silence",
    notes: "",
  },
  {
    id: "w390",
    name: "The Asylum",
    venue: "13th Gate Escape",
    city: "Baton Rouge",
    state: "LA",
    country: "United States",
    lat: 30.4404782, lng: -91.1885761,
    url: "https://morty.app/attraction/390/the-asylum",
    notes: "",
  },
  {
    id: "w396",
    name: "Tomb Of Anubis",
    venue: "13th Gate Escape",
    city: "Baton Rouge",
    state: "LA",
    country: "United States",
    lat: 30.4404782, lng: -91.1885761,
    url: "https://morty.app/attraction/396/tomb-of-anubis",
    notes: "",
  },
  {
    id: "w618",
    name: "Ruins of the Mystic Temple",
    venue: "Rabbit Hole Recreation Services",
    city: "Louisville",
    state: "CO",
    country: "United States",
    lat: 39.9607742, lng: -105.1666727,
    url: "https://morty.app/attraction/618/ruins-of-the-mystic-temple",
    notes: "",
  },
  {
    id: "w1432",
    name: "The Vanishing Act",
    venue: "Locurio",
    city: "Seattle",
    state: "WA",
    country: "United States",
    lat: 47.650144, lng: -122.3502762,
    url: "https://morty.app/attraction/1432/the-vanishing-act",
    notes: "",
  },
  {
    id: "w1441",
    name: "Alien Invasion",
    venue: "Maine Escape Games",
    city: "South Portland",
    state: "ME",
    country: "United States",
    lat: 43.629433, lng: -70.328746,
    url: "https://morty.app/attraction/1441/alien-invasion",
    notes: "",
  },
  {
    id: "w2251",
    name: "Grandma's Surprise",
    venue: "Trapped! Escape Room - Los Angeles",
    city: "San Dimas",
    state: "CA",
    country: "United States",
    lat: 34.108989, lng: -117.822034,
    url: "https://morty.app/attraction/2251/grandmas-surprise",
    notes: "",
  },
  {
    id: "w2830",
    name: "Ripper",
    venue: "Nocturne Adventures",
    city: "Hickory",
    state: "NC",
    country: "United States",
    lat: 35.7977802, lng: -81.2566429,
    url: "https://morty.app/attraction/2830/ripper",
    notes: "",
  },
  {
    id: "w3082",
    name: "Room 303 - Chapter 1",
    venue: "303 Escape - Denver Escape Room",
    city: "Thornton",
    state: "CO",
    country: "United States",
    lat: 39.8571219, lng: -104.994769,
    url: "https://morty.app/attraction/3082/room-303-chapter-1",
    notes: "",
  },
  {
    id: "w3296",
    name: "Shipwreck Cove",
    venue: "Memphis Escape Rooms - South Main",
    city: "Memphis",
    state: "TN",
    country: "United States",
    lat: 35.1329879, lng: -90.058753,
    url: "https://morty.app/attraction/3296/shipwreck-cove",
    notes: "",
  },
  {
    id: "w3298",
    name: "Calling All Villains",
    venue: "CU Adventures in Time and Space",
    city: "Urbana",
    state: "IL",
    country: "United States",
    lat: 40.1154421, lng: -88.2062147,
    url: "https://morty.app/attraction/3298/calling-all-villains",
    notes: "",
  },
  {
    id: "w3362",
    name: "Experiment C73",
    venue: "Conundrum Escape Rooms - Arvada",
    city: "Arvada",
    state: "CO",
    country: "United States",
    lat: 39.8121768, lng: -105.0809981,
    url: "https://morty.app/attraction/3362/experiment-c73",
    notes: "",
  },
  {
    id: "w3402",
    name: "Ghost Light",
    venue: "MyssTic Rooms",
    city: "Brooklyn",
    state: "NY",
    country: "United States",
    lat: 40.674528, lng: -73.9762765,
    url: "https://morty.app/attraction/3402/ghost-light-lg6a",
    notes: "",
  },
  {
    id: "w3528",
    name: "The Landlord's Office",
    venue: "Exit Puzzles Escape Room",
    city: "Olympia",
    state: "WA",
    country: "United States",
    lat: 47.0439292, lng: -122.9021038,
    url: "https://morty.app/attraction/3528/the-landlords-office",
    notes: "",
  },
  {
    id: "w3551",
    name: "Cutthroat Cavern",
    venue: "13th Gate Escape",
    city: "Baton Rouge",
    state: "LA",
    country: "United States",
    lat: 30.4404782, lng: -91.1885761,
    url: "https://morty.app/attraction/3551/cutthroat-cavern",
    notes: "",
  },
  {
    id: "w3553",
    name: "Conundrum Museum",
    venue: "Boxaroo",
    city: "Boston",
    state: "MA",
    country: "United States",
    lat: 42.35934, lng: -71.05905,
    url: "https://morty.app/attraction/3553/conundrum-museum",
    notes: "",
  },
  {
    id: "w3733",
    name: "Captain Spoopy Bones and the Magnificent Quest For Some Other Pirate's Treasure!",
    venue: "Doldrick's Escape Room",
    city: "Kissimmee",
    state: "FL",
    country: "United States",
    lat: 28.335142, lng: -81.478393,
    url: "https://morty.app/attraction/3733/captain-spoopy-bones",
    notes: "",
  },
  {
    id: "w3828",
    name: "Hunting Dracula [Formerly \"V\"]",
    venue: "Locked Adventures",
    city: "San Marcos",
    state: "CA",
    country: "United States",
    lat: 33.1364909, lng: -117.1836969,
    url: "https://morty.app/attraction/3828/hunting-dracula-formerly-v",
    notes: "",
  },
  {
    id: "w3918",
    name: "Paradox | The Incredible Time Machine",
    venue: "Rabbit Hole Recreation Services",
    city: "Louisville",
    state: "CO",
    country: "United States",
    lat: 39.9607742, lng: -105.1666727,
    url: "https://morty.app/attraction/3918/paradox-the-incredible-time-machine",
    notes: "",
  },
  {
    id: "w3960",
    name: "The Man From Beyond",
    venue: "Strange Bird Immersive",
    city: "Houston",
    state: "TX",
    country: "United States",
    lat: 29.7851776, lng: -95.4452023,
    url: "https://morty.app/attraction/3960/the-man-from-beyond",
    notes: "",
  },
  {
    id: "w4030",
    name: "Hidden Temple",
    venue: "60 to Escape - Gurnee",
    city: "Gurnee",
    state: "IL",
    country: "United States",
    lat: 42.3915947, lng: -87.9583612,
    url: "https://morty.app/attraction/4030/hidden-temple",
    notes: "",
  },
  {
    id: "w4571",
    name: "Escape Your Fears",
    venue: "Maine Escape Games",
    city: "South Portland",
    state: "ME",
    country: "United States",
    lat: 43.629433, lng: -70.328746,
    url: "https://morty.app/attraction/4571/escape-your-fears",
    notes: "",
  },
  {
    id: "w4572",
    name: "Uncle Ned's Cabin",
    venue: "Maine Escape Games",
    city: "South Portland",
    state: "ME",
    country: "United States",
    lat: 43.629433, lng: -70.328746,
    url: "https://morty.app/attraction/4572/uncle-neds-cabin",
    notes: "",
  },
  {
    id: "w4755",
    name: "The Bayou: The Legend of the Midnight Raven",
    venue: "The Entrapment",
    city: "San Diego",
    state: "CA",
    country: "United States",
    lat: 32.8241451, lng: -117.1508995,
    url: "https://morty.app/attraction/4755/the-bayou-the-legend-of-the-midnight-raven",
    notes: "",
  },
  {
    id: "w4756",
    name: "The Disappearance at Fogmore Manor",
    venue: "The Entrapment",
    city: "San Diego",
    state: "CA",
    country: "United States",
    lat: 32.8241451, lng: -117.1508995,
    url: "https://morty.app/attraction/4756/the-disappearance-at-fogmore-manor",
    notes: "",
  },
  {
    id: "w4769",
    name: "The Observatory",
    venue: "The Gate Escape",
    city: "Leominster",
    state: "MA",
    country: "United States",
    lat: 42.5237274, lng: -71.7175369,
    url: "https://morty.app/attraction/4769/the-observatory",
    notes: "",
  },
  {
    id: "w4825",
    name: "The Passage",
    venue: "Twisted Limits Escape Rooms",
    city: "McHenry",
    state: "IL",
    country: "United States",
    lat: 42.3444452, lng: -88.2709899,
    url: "https://morty.app/attraction/4825/the-passage",
    notes: "",
  },
  {
    id: "w6072",
    name: "Storyteller's Secret",
    venue: "Boxaroo",
    city: "Boston",
    state: "MA",
    country: "United States",
    lat: 42.35934, lng: -71.05905,
    url: "https://morty.app/attraction/6072/storytellers-secret",
    notes: "",
  },
  {
    id: "w6242",
    name: "Return of the Pharaohs",
    venue: "Paragon Escape Games",
    city: "Mesa",
    state: "AZ",
    country: "United States",
    lat: 33.2838898, lng: -111.6409845,
    url: "https://morty.app/attraction/6242/return-of-the-pharaohs",
    notes: "",
  },
  {
    id: "w6312",
    name: "The Museum Of Curiosity",
    venue: "Exit Puzzles Escape Room",
    city: "Olympia",
    state: "WA",
    country: "United States",
    lat: 47.0439292, lng: -122.9021038,
    url: "https://morty.app/attraction/6312/the-museum-of-curiosity",
    notes: "",
  },
  {
    id: "w6384",
    name: "Frost Base Z",
    venue: "Rabbit Hole Recreation Services",
    city: "Louisville",
    state: "CO",
    country: "United States",
    lat: 39.9607742, lng: -105.1666727,
    url: "https://morty.app/attraction/6384/frost-base-z",
    notes: "",
  },
  {
    id: "w6497",
    name: "Southport School for Wizards",
    venue: "Maine Escape Games",
    city: "South Portland",
    state: "ME",
    country: "United States",
    lat: 43.629433, lng: -70.328746,
    url: "https://morty.app/attraction/6497/southport-school-for-wizards",
    notes: "",
  },
  {
    id: "w6589",
    name: "Chaos In The Galleria",
    venue: "Omescape - Sunnyvale",
    city: "Sunnyvale",
    state: "CA",
    country: "United States",
    lat: 37.3810948, lng: -121.9995181,
    url: "https://morty.app/attraction/6589/chaos-in-the-galleria",
    notes: "",
  },
  {
    id: "w6671",
    name: "Black and White Cafe",
    venue: "MindFox Escape",
    city: "San Diego",
    state: "CA",
    country: "United States",
    lat: 32.8904936, lng: -117.1629173,
    url: "https://morty.app/attraction/6671/black-and-white-cafe",
    notes: "",
  },
  {
    id: "w6679",
    name: "The Seventh Room",
    venue: "Dare 2 Escape",
    city: "Kissimmee",
    state: "FL",
    country: "United States",
    lat: 28.3336216, lng: -81.4861852,
    url: "https://morty.app/attraction/6679/the-seventh-room",
    notes: "",
  },
  {
    id: "w6682",
    name: "London Fog: The Mists of Time",
    venue: "The Entrapment",
    city: "San Diego",
    state: "CA",
    country: "United States",
    lat: 32.8241451, lng: -117.1508995,
    url: "https://morty.app/attraction/6682/london-fog-the-mists-of-time",
    notes: "",
  },
  {
    id: "w6989",
    name: "The Reel",
    venue: "Puzzle Effect - Clovis",
    city: "Clovis",
    state: "CA",
    country: "United States",
    lat: 36.8081625, lng: -119.7054113,
    url: "https://morty.app/attraction/6989/the-reel",
    notes: "",
  },
  {
    id: "w7199",
    name: "A Twist Of Oz",
    venue: "Key to Escape",
    city: "Statesville",
    state: "NC",
    country: "United States",
    lat: 35.782005, lng: -80.8844383,
    url: "https://morty.app/attraction/7199/a-twist-of-oz",
    notes: "",
  },
  {
    id: "w7200",
    name: "Under Pressure",
    venue: "Key to Escape",
    city: "Statesville",
    state: "NC",
    country: "United States",
    lat: 35.782005, lng: -80.8844383,
    url: "https://morty.app/attraction/7200/under-pressure",
    notes: "",
  },
  {
    id: "w7206",
    name: "Murder Mansion",
    venue: "Countdown Games",
    city: "Lexington",
    state: "KY",
    country: "United States",
    lat: 38.0171198, lng: -84.417211,
    url: "https://morty.app/attraction/7206/murder-mansion",
    notes: "",
  },
  {
    id: "w7362",
    name: "EVIL Robots",
    venue: "The Nemesis Club",
    city: "Phoenix",
    state: "AZ",
    country: "United States",
    lat: 33.6762339, lng: -111.9654516,
    url: "https://morty.app/attraction/7362/evil-robots",
    notes: "",
  },
  {
    id: "w7482",
    name: "Hide + Seek",
    venue: "The Escape Warehouse",
    city: "Ponchatoula",
    state: "LA",
    country: "United States",
    lat: 30.4345282, lng: -90.4405458,
    url: "https://morty.app/attraction/7482/hide-seek",
    notes: "",
  },
  {
    id: "w7954",
    name: "Cybercity 2049",
    venue: "Escape Barcelona 2 3",
    city: "Santa Coloma de Gramenet",
    state: "",
    country: "Spain",
    lat: 41.4493116, lng: 2.2093289,
    url: "https://morty.app/attraction/7954/cybercity-2049",
    notes: "",
  },
  {
    id: "w8123",
    name: "Game Night",
    venue: "CU Adventures in Time and Space",
    city: "Urbana",
    state: "IL",
    country: "United States",
    lat: 40.1154421, lng: -88.2062147,
    url: "https://morty.app/attraction/8123/game-night",
    notes: "",
  },
  {
    id: "w8502",
    name: "Paradox Project 2: Το Βιβλιοπωλείον [The Bookstore]",
    venue: "Paradox Project",
    city: "Athens",
    state: "",
    country: "Greece",
    lat: 37.9601374, lng: 23.7076769,
    url: "https://morty.app/attraction/8502/paradox-project-2-to-bibliopoleion-the-bookstore",
    notes: "",
  },
  {
    id: "w9165",
    name: "Wong's Chinese",
    venue: "The Perfect Escape",
    city: "Arlington",
    state: "TX",
    country: "United States",
    lat: 32.7676663, lng: -97.0654786,
    url: "https://morty.app/attraction/9165/wongs-chinese",
    notes: "",
  },
  {
    id: "w9185",
    name: "13th Basement",
    venue: "Exit Game OC - Anaheim",
    city: "Anaheim",
    state: "CA",
    country: "United States",
    lat: 33.8475999, lng: -117.8610564,
    url: "https://morty.app/attraction/9185/the-13th-basement",
    notes: "",
  },
  {
    id: "w9310",
    name: "Dragon Tower",
    venue: "Legend X - Rowland Heights, CA",
    city: "Rowland Heights",
    state: "CA",
    country: "United States",
    lat: 33.9934187, lng: -117.9284431,
    url: "https://morty.app/attraction/9310/dragon-tower",
    notes: "",
  },
  {
    id: "w9312",
    name: "Dr. Gem’s Time Trap",
    venue: "Maine Escape Games",
    city: "South Portland",
    state: "ME",
    country: "United States",
    lat: 43.629433, lng: -70.328746,
    url: "https://morty.app/attraction/9312/dr-gems-time-trap",
    notes: "",
  },
  {
    id: "w9443",
    name: "Le Grand Immersia Hotel [The Grand Immersia Hotel]",
    venue: "Immersia Escape Games",
    city: "Laval",
    state: "",
    country: "Canada",
    lat: 45.5881594, lng: -73.7467491,
    url: "https://morty.app/attraction/9443/the-grand-immersia-hotel",
    notes: "",
  },
  {
    id: "w9445",
    name: "L'institut Salutem Medicina [Salutem Medicina Institute]",
    venue: "Immersia Escape Games",
    city: "Laval",
    state: "",
    country: "Canada",
    lat: 45.5881594, lng: -73.7467491,
    url: "https://morty.app/attraction/9445/linstitut-salutem-medicina-salutem-medicina-institute",
    notes: "",
  },
  {
    id: "w9772",
    name: "Mogollon Monster: Scouting for Arizona's Bigfoot",
    venue: "The Nemesis Club",
    city: "Phoenix",
    state: "AZ",
    country: "United States",
    lat: 33.6762339, lng: -111.9654516,
    url: "https://morty.app/attraction/9772/mogollon-monster-scouting-for-arizonas-bigfoot",
    notes: "",
  },
  {
    id: "w9824",
    name: "Le Cinéma de M. Trippolyte [Mr Trippolyte's Cinema]",
    venue: "Grand Trip Trap Hotel",
    city: "Carouge",
    state: "",
    country: "Switzerland",
    lat: 46.186274, lng: 6.1439217,
    url: "https://morty.app/attraction/9824/le-cinema-de-m-trippolyte-mr-trippolytes-cinema",
    notes: "",
  },
  {
    id: "w9931",
    name: "The Tipsy Tailor",
    venue: "Intrepid Escape Rooms",
    city: "Tustin",
    state: "CA",
    country: "United States",
    lat: 33.7201612, lng: -117.8257287,
    url: "https://morty.app/attraction/9931/the-tipsy-tailor",
    notes: "",
  },
  {
    id: "w9996",
    name: "The Attraction",
    venue: "Palace Games",
    city: "San Francisco",
    state: "CA",
    country: "United States",
    lat: 37.8032375, lng: -122.449309,
    url: "https://morty.app/attraction/9996/the-attraction",
    notes: "",
  },
  {
    id: "w10123",
    name: "The Last Job",
    venue: "Confusion Escapes",
    city: "San Bernardino",
    state: "CA",
    country: "United States",
    lat: 34.0625808, lng: -117.2809876,
    url: "https://morty.app/attraction/10123/the-last-job",
    notes: "",
  },
  {
    id: "w10151",
    name: "Elevate: Skylounge",
    venue: "Wild Goose Escapes - Irvine",
    city: "Irvine",
    state: "CA",
    country: "United States",
    lat: 33.6877021, lng: -117.8341804,
    url: "https://morty.app/attraction/10151/elevate",
    notes: "",
  },
  {
    id: "w10187",
    name: "Undercooked",
    venue: "Omescape - Sunnyvale",
    city: "Sunnyvale",
    state: "CA",
    country: "United States",
    lat: 37.3810948, lng: -121.9995181,
    url: "https://morty.app/attraction/10187/undercooked",
    notes: "",
  },
  {
    id: "w10895",
    name: "Crane Manor",
    venue: "Clue IQ",
    city: "Frederick",
    state: "MD",
    country: "United States",
    lat: 39.4114062, lng: -77.4083367,
    url: "https://morty.app/attraction/10895/crane-manor",
    notes: "",
  },
  {
    id: "w11273",
    name: "The Battle for Britain",
    venue: "Escape Plan",
    city: "Lexington",
    state: "SC",
    country: "United States",
    lat: 34.0137806, lng: -81.144535,
    url: "https://morty.app/attraction/11273/the-battle-for-britain",
    notes: "",
  },
  {
    id: "w11847",
    name: "Molly's Game",
    venue: "Untold Stories Experiences [prev. Down the Hatch]",
    city: "Voorburg",
    state: "",
    country: "Netherlands",
    lat: 52.0840536, lng: 4.3610855,
    url: "https://morty.app/attraction/11847/mollys-game",
    notes: "",
  },
  {
    id: "w11853",
    name: "Japanese Massage Center | Tao Room Escape",
    venue: "Tao Room Escape",
    city: "Calella",
    state: "",
    country: "Spain",
    lat: 41.6193071, lng: 2.6651136,
    url: "https://morty.app/attraction/11853/tao-room-escape",
    notes: "",
  },
  {
    id: "w13593",
    name: "The Lost Dutchman's Mine v. 2.0",
    venue: "The Sanctuary Escape Games",
    city: "Oklahoma City",
    state: "OK",
    country: "United States",
    lat: 35.461513, lng: -97.6489058,
    url: "https://morty.app/attraction/13593/the-lost-dutchmans-mine-v-20",
    notes: "",
  },
  {
    id: "w13854",
    name: "Operation Gryaznayavoda",
    venue: "In Search Of An Exit",
    city: "Portland",
    state: "OR",
    country: "United States",
    lat: 45.534972, lng: -122.620762,
    url: "https://morty.app/attraction/13854/operation-gryaznayavoda",
    notes: "",
  },
  {
    id: "w13986",
    name: "Dark Heart of the Hotel - Chapter 2",
    venue: "303 Escape - Denver Escape Room",
    city: "Thornton",
    state: "CO",
    country: "United States",
    lat: 39.8571219, lng: -104.994769,
    url: "https://morty.app/attraction/13986/dark-heart-of-the-hotel-chapter-2",
    notes: "",
  },
  {
    id: "w14045",
    name: "Conjured Kingdoms",
    venue: "Alaska Escape Rooms",
    city: "Anchorage",
    state: "AK",
    country: "United States",
    lat: 61.2178192, lng: -149.8958435,
    url: "https://morty.app/attraction/14045/conjured-kingdoms",
    notes: "",
  },
  {
    id: "w14324",
    name: "The Isle of Wonder",
    venue: "The Greatest Escape",
    city: "Phoenix",
    state: "AZ",
    country: "United States",
    lat: 33.6393078, lng: -112.0574885,
    url: "https://morty.app/attraction/14324/the-isle-of-wonder",
    notes: "",
  },
  {
    id: "w14771",
    name: "S.A.S.H.A: Home Of The Future",
    venue: "Wild Goose Escapes - Fullerton",
    city: "Fullerton",
    state: "CA",
    country: "United States",
    lat: 33.872032, lng: -117.925247,
    url: "https://morty.app/attraction/14771/sasha-home-of-the-future",
    notes: "",
  },
  {
    id: "w14840",
    name: "Siren's Cove",
    venue: "Escape Hour Point Ruston",
    city: "Tacoma",
    state: "WA",
    country: "United States",
    lat: 47.2980972, lng: -122.5041802,
    url: "https://morty.app/attraction/14840/sirens-cove",
    notes: "",
  },
  {
    id: "w16836",
    name: "The Movies",
    venue: "The Push Mystery Rooms",
    city: "Bruges",
    state: "",
    country: "Belgium",
    lat: 51.2752858, lng: 3.2318031,
    url: "https://morty.app/attraction/16836/the-movies",
    notes: "",
  },
  {
    id: "w17078",
    name: "90s Nostalgia",
    venue: "Boxed In Escape Rooms - Festus",
    city: "Festus",
    state: "MO",
    country: "United States",
    lat: 38.2193746, lng: -90.3902316,
    url: "https://morty.app/attraction/17078/90s-nostalgia",
    notes: "",
  },
  {
    id: "w18099",
    name: "Hong Kong Afterdark",
    venue: "Omventure - Markham",
    city: "Markham",
    state: "",
    country: "Canada",
    lat: 43.8268996, lng: -79.3504763,
    url: "https://morty.app/attraction/18099/hong-kong-afterdark",
    notes: "",
  },
  {
    id: "w18728",
    name: "The Toy Factory",
    venue: "Tales of Torchdale [prev. Escaperoom Antwerp]",
    city: "Zoersel",
    state: "",
    country: "Belgium",
    lat: 51.2676746, lng: 4.7163728,
    url: "https://morty.app/attraction/18728/the-toy-factory",
    notes: "",
  },
  {
    id: "w20232",
    name: "Bites Motel",
    venue: "Bite The Fly",
    city: "Madrid",
    state: "",
    country: "Spain",
    lat: 40.3795557, lng: -3.6287499,
    url: "https://morty.app/attraction/20232/bites-motel",
    notes: "",
  },
  {
    id: "w20726",
    name: "Operation Arctic Storm: The Final Meltdown",
    venue: "The Escape Ventures - Orlando",
    city: "Orlando",
    state: "FL",
    country: "United States",
    lat: 28.5544338, lng: -81.2089538,
    url: "https://morty.app/attraction/20726/operation-arctic-storm-the-final-meltdown",
    notes: "",
  },
  {
    id: "w22998",
    name: "The Body Shop",
    venue: "Red Fox Escapes",
    city: "Cambridge",
    state: "MA",
    country: "United States",
    lat: 42.3649658, lng: -71.1034246,
    url: "https://morty.app/attraction/22998/the-body-shop",
    notes: "",
  },
  {
    id: "w23086",
    name: "Imertia",
    venue: "I-docens - World Escape",
    city: "Vernayaz",
    state: "",
    country: "Switzerland",
    lat: 46.1317532, lng: 7.04044,
    url: "https://morty.app/attraction/23086/imertia",
    notes: "",
  },
  {
    id: "w23906",
    name: "Neighborhood Watcher",
    venue: "The Escape Ventures - Orlando",
    city: "Orlando",
    state: "FL",
    country: "United States",
    lat: 28.5544338, lng: -81.2089538,
    url: "https://morty.app/attraction/23906/neighborhood-watcher",
    notes: "",
  },
  {
    id: "w24219",
    name: "Reich der Sinne [Realm Of The Senses]",
    venue: "Rotkreutzplatz Branch",
    city: "Munich",
    state: "",
    country: "Germany",
    lat: 48.1522272, lng: 11.5303331,
    url: "https://morty.app/attraction/24219/reich-der-sinne-realm-of-the-senses",
    notes: "",
  },
  {
    id: "w24742",
    name: "Birth Machine",
    venue: "Mad Machines",
    city: "Milan",
    state: "",
    country: "Italy",
    lat: 45.4435275, lng: 9.1557885,
    url: "https://morty.app/attraction/24742/birth-machine",
    notes: "",
  },
  {
    id: "w25809",
    name: "Chapter 2: Norcross Art Gallery",
    venue: "Off The Couch Games",
    city: "Fremont",
    state: "CA",
    country: "United States",
    lat: 37.5681468, lng: -121.9732099,
    url: "https://morty.app/attraction/25809/norcross-art-gallery",
    notes: "",
  },
  {
    id: "w26058",
    name: "L’échoppe De Madame Ming [Mrs Ming’s Old Shop]",
    venue: "L'Atelier des Énigmes Escape Game Annecy",
    city: "Annecy",
    state: "",
    country: "France",
    lat: 45.895918, lng: 6.1099433,
    url: "https://morty.app/attraction/26058/lechoppe-de-madame-ming-mrs-mings-old-shop",
    notes: "",
  },
  {
    id: "w26335",
    name: "The Treehouse",
    venue: "Confusion Escapes",
    city: "San Bernardino",
    state: "CA",
    country: "United States",
    lat: 34.0625808, lng: -117.2809876,
    url: "https://morty.app/attraction/26335/the-treehouse",
    notes: "",
  },
  {
    id: "w27934",
    name: "Shaky Grounds Cafe",
    venue: "Shaky Grounds Cafe",
    city: "Portland",
    state: "OR",
    country: "United States",
    lat: 45.4737103, lng: -122.6618989,
    url: "https://morty.app/attraction/27934/shaky-grounds-cafe-portable",
    notes: "",
  },
  {
    id: "w27935",
    name: "Search For Sasquatch",
    venue: "Boxed In Escape Rooms - Festus",
    city: "Festus",
    state: "MO",
    country: "United States",
    lat: 38.2193746, lng: -90.3902316,
    url: "https://morty.app/attraction/27935/search-for-sasquatch",
    notes: "",
  },
  {
    id: "w29517",
    name: "The Invisible Man",
    venue: "13th Room",
    city: "Pomona",
    state: "CA",
    country: "United States",
    lat: 34.0571687, lng: -117.7497801,
    url: "https://morty.app/attraction/29517/the-invisible-man",
    notes: "",
  },
  {
    id: "w29633",
    name: "Abstraction",
    venue: "Eliviascape",
    city: "Quebec City",
    state: "",
    country: "Canada",
    lat: 46.7741249, lng: -71.2982448,
    url: "https://morty.app/attraction/29633/abstraction",
    notes: "",
  },
  {
    id: "w29639",
    name: "De Wraak Van Han [Han’s Revenge]",
    venue: "De Gouden Kooi",
    city: "Mechelen",
    state: "",
    country: "Belgium",
    lat: 51.0264232, lng: 4.4755305,
    url: "https://morty.app/attraction/29639/de-wraak-van-han-hans-revenge",
    notes: "",
  },
  {
    id: "w29685",
    name: "The Jurassic Project",
    venue: "Memphis Escape Rooms - South Main",
    city: "Memphis",
    state: "TN",
    country: "United States",
    lat: 35.1329879, lng: -90.058753,
    url: "https://morty.app/attraction/29685/the-jurassic-project",
    notes: "",
  },
  {
    id: "w30238",
    name: "The Seed Of Hope",
    venue: "The Sanctuary Escape Games",
    city: "Oklahoma City",
    state: "OK",
    country: "United States",
    lat: 35.461513, lng: -97.6489058,
    url: "https://morty.app/attraction/30238/the-seed-of-hope",
    notes: "",
  },
  {
    id: "w30720",
    name: "Madness: 1917",
    venue: "Doors of Divergence",
    city: "Charlotte",
    state: "NC",
    country: "United States",
    lat: 35.2248315, lng: -80.8207246,
    url: "https://morty.app/attraction/30720/madness-1917",
    notes: "",
  },
  {
    id: "w31200",
    name: "Sal's Cybernetics",
    venue: "The Immersive Machine",
    city: "Phoenix",
    state: "AZ",
    country: "United States",
    lat: 33.4649624, lng: -111.9875606,
    url: "https://morty.app/attraction/31200/sals-cybernetics",
    notes: "",
  },
  {
    id: "w31391",
    name: "Awakened 2.0",
    venue: "Chronos Escape Room",
    city: "Pomona",
    state: "CA",
    country: "United States",
    lat: 34.0624037, lng: -117.7866675,
    url: "https://morty.app/attraction/31391/awakened-20",
    notes: "",
  },
  {
    id: "w31785",
    name: "Temple Of Doom",
    venue: "Operation Outbreak",
    city: "El Paso",
    state: "TX",
    country: "United States",
    lat: 31.7835, lng: -106.4357861,
    url: "https://morty.app/attraction/31785/temple-of-doom",
    notes: "",
  },
  {
    id: "w32325",
    name: "Vanishing Act",
    venue: "Black Mountain Escape",
    city: "Black Mountain",
    state: "NC",
    country: "United States",
    lat: 35.6152544, lng: -82.3203891,
    url: "https://morty.app/attraction/32325/vanishing-act",
    notes: "",
  },
  {
    id: "w32692",
    name: "Guardians' Grove",
    venue: "Sure Lock Escapes – Cypher Island (Renton)",
    city: "Renton",
    state: "WA",
    country: "United States",
    lat: 47.449648, lng: -122.1854144,
    url: "https://morty.app/attraction/32692/guardians-grove",
    notes: "",
  },
  {
    id: "w32719",
    name: "Rise Of The Icarus",
    venue: "CU Adventures in Time and Space",
    city: "Urbana",
    state: "IL",
    country: "United States",
    lat: 40.1154421, lng: -88.2062147,
    url: "https://morty.app/attraction/32719/rise-of-the-icarus",
    notes: "",
  },
  {
    id: "w33046",
    name: "45 Lampkin Lane",
    venue: "Confusion Escapes",
    city: "San Bernardino",
    state: "CA",
    country: "United States",
    lat: 34.0625808, lng: -117.2809876,
    url: "https://morty.app/attraction/33046/45-lampkin-lane",
    notes: "",
  },
  {
    id: "w33408",
    name: "The Hot Dog Heist",
    venue: "Trapology Boston",
    city: "Boston",
    state: "MA",
    country: "United States",
    lat: 42.3530231, lng: -71.0642354,
    url: "https://morty.app/attraction/33408/the-hot-dog-heist",
    notes: "",
  },
  {
    id: "w33960",
    name: "Una Aventura De Leyenda [A Legendary Adventure]",
    venue: "Mayto Kingdom",
    city: "Vitoria-Gasteiz",
    state: "",
    country: "Spain",
    lat: 42.8732465, lng: -2.650125,
    url: "https://morty.app/attraction/33960/an-adventure-of-legend-an-adventure-of-legend",
    notes: "",
  },
  {
    id: "w33968",
    name: "Projet R.E.S.E.T. [Project R.E.S.E.T.]",
    venue: "Immersia Escape Games",
    city: "Laval",
    state: "",
    country: "Canada",
    lat: 45.5881594, lng: -73.7467491,
    url: "https://morty.app/attraction/33968/projet-reset",
    notes: "",
  },
  {
    id: "w34180",
    name: "Robotopia",
    venue: "Omescape - Sunnyvale",
    city: "Sunnyvale",
    state: "CA",
    country: "United States",
    lat: 37.3810948, lng: -121.9995181,
    url: "https://morty.app/attraction/34180/robotopia",
    notes: "",
  },
  {
    id: "w34254",
    name: "Demise of the Gricers",
    venue: "Entered",
    city: "As",
    state: "",
    country: "Belgium",
    lat: 51.005553, lng: 5.6028997,
    url: "https://morty.app/attraction/34254/demise-of-the-gricers-7m6q",
    notes: "",
  },
  {
    id: "w34866",
    name: "Wizard's Treasure",
    venue: "60Out - Hollywood",
    city: "Los Angeles",
    state: "CA",
    country: "United States",
    lat: 34.095432, lng: -118.309021,
    url: "https://morty.app/attraction/34866/wizards-treasure",
    notes: "",
  },
  {
    id: "w34891",
    name: "Chapter 3: The Morgue",
    venue: "Off The Couch Games",
    city: "Fremont",
    state: "CA",
    country: "United States",
    lat: 37.5681468, lng: -121.9732099,
    url: "https://morty.app/attraction/34891/morgue",
    notes: "",
  },
  {
    id: "w35041",
    name: "Cold Case",
    venue: "Cloud Escape",
    city: "Anaheim",
    state: "CA",
    country: "United States",
    lat: 33.8604248, lng: -117.78775,
    url: "https://morty.app/attraction/35041/cold-case",
    notes: "",
  },
  {
    id: "w35765",
    name: "The Basement",
    venue: "Intense Escape - Tampa Location",
    city: "Tampa",
    state: "FL",
    country: "United States",
    lat: 27.9477283, lng: -82.348191,
    url: "https://morty.app/attraction/35765/the-basement",
    notes: "",
  },
  {
    id: "w35784",
    name: "La Maison de Tonton Cornelius [The House of Uncle Cornelius]",
    venue: "Grand Trip Trap Hotel",
    city: "Carouge",
    state: "",
    country: "Switzerland",
    lat: 46.186274, lng: 6.1439217,
    url: "https://morty.app/attraction/35784/la-maison-de-tonton-cornelius-the-house-of-uncle-cornelius",
    notes: "",
  },
  {
    id: "w36629",
    name: "Phantom Files: The Investigation Of Lockturne Manor",
    venue: "The Escape Ventures - Port Charlotte",
    city: "Port Charlotte",
    state: "FL",
    country: "United States",
    lat: 26.9862999, lng: -82.1012028,
    url: "https://morty.app/attraction/36629/phantom-files-the-investigation-of-lockturne-manor",
    notes: "",
  },
  {
    id: "w36633",
    name: "Secret Tales",
    venue: "Next Level Escape",
    city: "Hamilton",
    state: "",
    country: "Canada",
    lat: 43.2212375, lng: -79.8844382,
    url: "https://morty.app/attraction/36633/secret-tales",
    notes: "",
  },
  {
    id: "w36988",
    name: "La Peluquería [The Hairdressing]",
    venue: "The X-Door Valencia",
    city: "Valencia",
    state: "",
    country: "Spain",
    lat: 39.4723227, lng: -0.3898523,
    url: "https://morty.app/attraction/36988/la-peluqueria-the-hairdressing",
    notes: "",
  },
  {
    id: "w37006",
    name: "Opus Memori",
    venue: "Ezkapaz",
    city: "Montreal",
    state: "",
    country: "Canada",
    lat: 45.5164993, lng: -73.5780871,
    url: "https://morty.app/attraction/37006/opus-memori",
    notes: "",
  },
  {
    id: "w37605",
    name: "Shimmer Reef",
    venue: "Sure Lock Escapes – Cypher Island (Renton)",
    city: "Renton",
    state: "WA",
    country: "United States",
    lat: 47.449648, lng: -122.1854144,
    url: "https://morty.app/attraction/37605/shimmer-reef",
    notes: "",
  },
  {
    id: "w38069",
    name: "Cheesie's Pizza Party",
    venue: "60 to Escape - Schaumburg",
    city: "Schaumburg",
    state: "IL",
    country: "United States",
    lat: 42.0464767, lng: -88.0372089,
    url: "https://morty.app/attraction/38069/cheesies-pizza-party",
    notes: "",
  },
  {
    id: "w40483",
    name: "Nevermore",
    venue: "Nocturne Adventures",
    city: "Hickory",
    state: "NC",
    country: "United States",
    lat: 35.7977802, lng: -81.2566429,
    url: "https://morty.app/attraction/40483/nevermore",
    notes: "",
  },
  {
    id: "w40503",
    name: "Back to Childhood",
    venue: "Clockwise Escape Room - Pleasanton",
    city: "Pleasanton",
    state: "CA",
    country: "United States",
    lat: 37.6577701, lng: -121.8762172,
    url: "https://morty.app/attraction/40503/back-to-childhood",
    notes: "",
  },
  {
    id: "w42141",
    name: "Haunting at Haruka High",
    venue: "Omescape - Sunnyvale",
    city: "Sunnyvale",
    state: "CA",
    country: "United States",
    lat: 37.3810948, lng: -121.9995181,
    url: "https://morty.app/attraction/42141/haunting-at-haruka-high",
    notes: "",
  },
  {
    id: "w42300",
    name: "The Silence 2: The Killing Words",
    venue: "13th Room",
    city: "Pomona",
    state: "CA",
    country: "United States",
    lat: 34.0571687, lng: -117.7497801,
    url: "https://morty.app/attraction/42300/the-silence-2-the-killing-words-nwkw",
    notes: "",
  },
  {
    id: "w43672",
    name: "Clark's Crazy Christmas",
    venue: "Exodus Escape Room",
    city: "Anaheim",
    state: "CA",
    country: "United States",
    lat: 33.8586169, lng: -117.7911937,
    url: "https://morty.app/attraction/43672/clarks-crazy-christmas",
    notes: "",
  },
  {
    id: "w44356",
    name: "The Candy Shoppe",
    venue: "PuzzleConnect Escape Rooms",
    city: "Holmdel",
    state: "NJ",
    country: "United States",
    lat: 40.4165627, lng: -74.1599764,
    url: "https://morty.app/attraction/44356/the-candy-shoppe",
    notes: "",
  },
  {
    id: "w44426",
    name: "The Founder's Secret",
    venue: "The Lodge of Lazarus Crowe",
    city: "St Paul",
    state: "MN",
    country: "United States",
    lat: 44.9357657, lng: -93.114429,
    url: "https://morty.app/attraction/44426/the-founders-secret",
    notes: "",
  },
  {
    id: "w44944",
    name: "La Taberna",
    venue: "The City Escape Room By Experiencity",
    city: "Madrid",
    state: "",
    country: "Spain",
    lat: 40.4093346, lng: -3.7064017,
    url: "https://morty.app/attraction/44944/la-taberna-the-bar",
    notes: "",
  },
  {
    id: "w45020",
    name: "Click 'N Glitch Arcade Palace",
    venue: "The Escape Ventures - Port Charlotte",
    city: "Port Charlotte",
    state: "FL",
    country: "United States",
    lat: 26.9862999, lng: -82.1012028,
    url: "https://morty.app/attraction/45020/click-n-glitch-arcade-palace",
    notes: "",
  },
  {
    id: "w45123",
    name: "Kaleidoskop 1963 [Kaleidoscope 1963]",
    venue: "Time Maze",
    city: "Baden",
    state: "",
    country: "Switzerland",
    lat: 47.4774558, lng: 8.308797,
    url: "https://morty.app/attraction/45123/kaleidoskop-1963-kaleidoscope-1963-fpn5",
    notes: "",
  },
  {
    id: "w45171",
    name: "K.O.N.G. Protocol",
    venue: "Escape Barcelona 2 3",
    city: "Santa Coloma de Gramenet",
    state: "",
    country: "Spain",
    lat: 41.4493116, lng: 2.2093289,
    url: "https://morty.app/attraction/45171/kong-protocol",
    notes: "",
  },
  {
    id: "w45784",
    name: "Dragon Realm",
    venue: "Mile High Escape Ops",
    city: "Brighton",
    state: "CO",
    country: "United States",
    lat: 39.98577, lng: -104.7926685,
    url: "https://morty.app/attraction/45784/dragon-realm",
    notes: "",
  },
  {
    id: "w45875",
    name: "Nightfall: Creature At Camp Deadwood",
    venue: "The Escape Ventures - Port Charlotte",
    city: "Port Charlotte",
    state: "FL",
    country: "United States",
    lat: 26.9862999, lng: -82.1012028,
    url: "https://morty.app/attraction/45875/nightfall-creature-at-camp-deadwood",
    notes: "",
  },
  {
    id: "w46204",
    name: "Starship | Interstellar Escape",
    venue: "Wild Goose Escapes - Fullerton",
    city: "Fullerton",
    state: "CA",
    country: "United States",
    lat: 33.872032, lng: -117.925247,
    url: "https://morty.app/attraction/46204/starship",
    notes: "",
  },
  {
    id: "w46262",
    name: "Henchmen’s Heist",
    venue: "The Nemesis Club",
    city: "Phoenix",
    state: "AZ",
    country: "United States",
    lat: 33.6762339, lng: -111.9654516,
    url: "https://morty.app/attraction/46262/henchmens-heis",
    notes: "",
  },
  {
    id: "w46793",
    name: "Shhh!",
    venue: "The Escape Warehouse",
    city: "Ponchatoula",
    state: "LA",
    country: "United States",
    lat: 30.4345282, lng: -90.4405458,
    url: "https://morty.app/attraction/46793/shhh",
    notes: "",
  },
  {
    id: "w46968",
    name: "Cinema 7",
    venue: "Will To Escape - Orlando",
    city: "Orlando",
    state: "FL",
    country: "United States",
    lat: 28.4324049, lng: -81.4699214,
    url: "https://morty.app/attraction/46968/cinema-7-cult-classics",
    notes: "",
  },
  {
    id: "w48514",
    name: "Far-Fetched",
    venue: "Open Door Escape Games - Redlands",
    city: "Redlands",
    state: "CA",
    country: "United States",
    lat: 34.0657376, lng: -117.204956,
    url: "https://morty.app/attraction/48514/far-fetched",
    notes: "",
  },
  {
    id: "w49233",
    name: "Atraco al Compadre",
    venue: "Start Play",
    city: "Alcantarilla",
    state: "",
    country: "Spain",
    lat: 37.970702, lng: -1.2234821,
    url: "https://morty.app/attraction/49233/atraco-al-compadre",
    notes: "",
  },
  {
    id: "w49265",
    name: "Botanist Manor",
    venue: "Escape Rush",
    city: "Ixelles",
    state: "",
    country: "Belgium",
    lat: 50.819622, lng: 4.3888945,
    url: "https://morty.app/attraction/49265/botanist-manor",
    notes: "",
  },
  {
    id: "w50231",
    name: "Alone",
    venue: "Cloud Escape",
    city: "Anaheim",
    state: "CA",
    country: "United States",
    lat: 33.8604248, lng: -117.78775,
    url: "https://morty.app/attraction/50231/alone",
    notes: "",
  },
  {
    id: "w50408",
    name: "Jewel of the Sea",
    venue: "Intrepid Escape Rooms",
    city: "Tustin",
    state: "CA",
    country: "United States",
    lat: 33.7201612, lng: -117.8257287,
    url: "https://morty.app/attraction/50408/jewel-of-the-sea",
    notes: "",
  },
  {
    id: "w51061",
    name: "Zoltar Spreekt [Zoltar Speaks]",
    venue: "Escape Cafe Hilversum",
    city: "Hilversum",
    state: "",
    country: "Netherlands",
    lat: 52.2246419, lng: 5.1782237,
    url: "https://morty.app/attraction/51061/zoltar-spreekt",
    notes: "",
  },
  {
    id: "w51426",
    name: "Lockbuster Video",
    venue: "60 to Escape - Schaumburg",
    city: "Schaumburg",
    state: "IL",
    country: "United States",
    lat: 42.0464767, lng: -88.0372089,
    url: "https://morty.app/attraction/51426/lockbuster-video",
    notes: "",
  },
  {
    id: "w51540",
    name: "Monsters from the Abyss",
    venue: "Memphis Escape Rooms - East Memphis",
    city: "Memphis",
    state: "TN",
    country: "United States",
    lat: 35.1145348, lng: -89.8963324,
    url: "https://morty.app/attraction/51540/monsters-from-the-abyss",
    notes: "",
  },
  {
    id: "w51669",
    name: "Irvine School of Wizardry and the Goblin's Secrets",
    venue: "Hidden Donkey",
    city: "Irvine",
    state: "CA",
    country: "United States",
    lat: 33.6912107, lng: -117.8619224,
    url: "https://morty.app/attraction/51669/irvine-school-of-wizardry-and-the-goblins-secrets",
    notes: "",
  },
  {
    id: "w52116",
    name: "Lost Souls",
    venue: "Boxed In Escape Rooms - Festus",
    city: "Festus",
    state: "MO",
    country: "United States",
    lat: 38.2193746, lng: -90.3902316,
    url: "https://morty.app/attraction/52116/lost-souls",
    notes: "",
  },
  {
    id: "w52346",
    name: "Antenna Palace",
    venue: "Trapgame - Charrat",
    city: "Charrat",
    state: "",
    country: "Switzerland",
    lat: 46.1290601, lng: 7.1273468,
    url: "https://morty.app/attraction/52346/antenna-palace",
    notes: "",
  },
  {
    id: "w52508",
    name: "Arcadia ",
    venue: "Escape on 13th",
    city: "Salt Lake City",
    state: "UT",
    country: "United States",
    lat: 40.7419607, lng: -111.9017929,
    url: "https://morty.app/attraction/52508/arcadia",
    notes: "",
  },
  {
    id: "w52552",
    name: "Diamond Quest",
    venue: "Paranoia Quest - Tempe",
    city: "Tempe",
    state: "AZ",
    country: "United States",
    lat: 33.3410117, lng: -111.9668406,
    url: "https://morty.app/attraction/52552/diamond-quest",
    notes: "",
  },
  {
    id: "w53128",
    name: "Black Cat",
    venue: "Planet Escape Room",
    city: "Lomita",
    state: "CA",
    country: "United States",
    lat: 33.8046465, lng: -118.3260082,
    url: "https://morty.app/attraction/53128/black-cat",
    notes: "",
  },
  {
    id: "w53275",
    name: "Basement 2 Mama's House",
    venue: "Intense Escape - Tampa Location",
    city: "Tampa",
    state: "FL",
    country: "United States",
    lat: 27.9477283, lng: -82.348191,
    url: "https://morty.app/attraction/53275/basement-2-mamas-house",
    notes: "",
  },
  {
    id: "w53505",
    name: "Enter The Jungle",
    venue: "Enter Escape Room",
    city: "Riverside",
    state: "CA",
    country: "United States",
    lat: 33.9768759, lng: -117.337601,
    url: "https://morty.app/attraction/53505/enter-the-jungle",
    notes: "",
  },
  {
    id: "w53506",
    name: "Enter the Twisted Trials",
    venue: "Enter Escape Room",
    city: "Riverside",
    state: "CA",
    country: "United States",
    lat: 33.9768759, lng: -117.337601,
    url: "https://morty.app/attraction/53506/enter-the-twisted-trials",
    notes: "",
  },
  {
    id: "w53507",
    name: "Enter the Dark Wizard's Pursuit",
    venue: "Enter Escape Room",
    city: "Riverside",
    state: "CA",
    country: "United States",
    lat: 33.9768759, lng: -117.337601,
    url: "https://morty.app/attraction/53507/enter-the-dark-wizards-pursuit",
    notes: "",
  },
  {
    id: "w53761",
    name: "The Bird",
    venue: "MyssTic Rooms",
    city: "Brooklyn",
    state: "NY",
    country: "United States",
    lat: 40.674528, lng: -73.9762765,
    url: "https://morty.app/attraction/53761/the-bird-evuy",
    notes: "",
  },
  {
    id: "w53811",
    name: "The Fortune Teller",
    venue: "No. 1 Escapes - Sky Park",
    city: "Irvine",
    state: "CA",
    country: "United States",
    lat: 33.68798, lng: -117.858187,
    url: "https://morty.app/attraction/53811/the-fortune-teller",
    notes: "",
  },
  {
    id: "w53827",
    name: "Missing at the Mortuary",
    venue: "Missing at the Mortuary",
    city: "Pasadena",
    state: "CA",
    country: "United States",
    lat: 34.1581968, lng: -118.1420682,
    url: "https://morty.app/attraction/53827/missing-at-the-mortuary",
    notes: "",
  },
  {
    id: "w54031",
    name: "Witch's Hollow",
    venue: "Stained Hourglass Escapes LLC.",
    city: "Salem",
    state: "MA",
    country: "United States",
    lat: 42.5190773, lng: -70.8949355,
    url: "https://morty.app/attraction/54031/witchs-hollow",
    notes: "",
  },
  {
    id: "w54327",
    name: "Henry's Birthday",
    venue: "The Missing Link",
    city: "Geel",
    state: "",
    country: "Belgium",
    lat: 51.1474465, lng: 4.9590348,
    url: "https://morty.app/attraction/54327/henrys-birthday",
    notes: "",
  },
  {
    id: "w54402",
    name: "Exodus ",
    venue: "Elements Escape Rooms [prev. Action Room Escape]",
    city: "Barcelona",
    state: "",
    country: "Spain",
    lat: 41.3702324, lng: 2.1357425,
    url: "https://morty.app/attraction/54402/exodus",
    notes: "",
  },
  {
    id: "w54705",
    name: "Witchly Ever After",
    venue: "Omescape - San Jose",
    city: "San Jose",
    state: "CA",
    country: "United States",
    lat: 37.3147229, lng: -121.8516703,
    url: "https://morty.app/attraction/54705/witchly-ever-after",
    notes: "",
  },
  {
    id: "w54885",
    name: "The Forest of Fables",
    venue: "CU Adventures in Time and Space",
    city: "Urbana",
    state: "IL",
    country: "United States",
    lat: 40.1154421, lng: -88.2062147,
    url: "https://morty.app/attraction/54885/the-forest-of-fables",
    notes: "",
  },
  {
    id: "w54940",
    name: "Cornstalkers: Lost in the Maize",
    venue: "The Escape Ventures - Orlando",
    city: "Orlando",
    state: "FL",
    country: "United States",
    lat: 28.5544338, lng: -81.2089538,
    url: "https://morty.app/attraction/54940/cornstalkers-lost-in-the-maize",
    notes: "",
  },
  {
    id: "w54984",
    name: "The Mole of The Mountain",
    venue: "Upside Down Escape Games",
    city: "Mashpee",
    state: "MA",
    country: "United States",
    lat: 41.6153155, lng: -70.492224,
    url: "https://morty.app/attraction/54984/the-mole-of-the-mountain",
    notes: "",
  },
  {
    id: "w55092",
    name: "Le Jardin de Madame Suzette [The Garden of Madame Suzette]",
    venue: "Grand Trip Trap Hotel",
    city: "Carouge",
    state: "",
    country: "Switzerland",
    lat: 46.186274, lng: 6.1439217,
    url: "https://morty.app/attraction/55092/le-jardin-de-madame-suzette-the-garden-of-madame-suzette",
    notes: "",
  },
  {
    id: "w55418",
    name: "Monster Mashers",
    venue: "Tales of Torchdale - Monster Mashers",
    city: "Zoersel",
    state: "",
    country: "Belgium",
    lat: 51.2676746, lng: 4.7163728,
    url: "https://morty.app/attraction/55418/monster-mashers",
    notes: "",
  },
  {
    id: "w55767",
    name: "Undercooked",
    venue: "Saber Room Escape",
    city: "San Bernardino",
    state: "CA",
    country: "United States",
    lat: 34.0627077, lng: -117.280598,
    url: "https://morty.app/attraction/55767/undercooked",
    notes: "",
  },
  {
    id: "w56994",
    name: "La Llorona",
    venue: "Operation Outbreak",
    city: "El Paso",
    state: "TX",
    country: "United States",
    lat: 31.7835, lng: -106.4357861,
    url: "https://morty.app/attraction/56994/la-llorona",
    notes: "",
  },
  {
    id: "w57159",
    name: "Elixir",
    venue: "Exodus Escape Room - Anaheim Hills, CA",
    city: "Anaheim",
    state: "CA",
    country: "United States",
    lat: 33.8586169, lng: -117.7911937,
    url: "https://morty.app/attraction/57159/elixir",
    notes: "",
  },
  {
    id: "w58946",
    name: "Cartel",
    venue: "Operation Outbreak",
    city: "El Paso",
    state: "TX",
    country: "United States",
    lat: 31.7835, lng: -106.4357861,
    url: "https://morty.app/attraction/58946/cartel",
    notes: "",
  },
  {
    id: "w60986",
    name: "La Tienda de Te dell Sr Miyagi",
    venue: "Don Escape",
    city: "Valencia",
    state: "",
    country: "Spain",
    lat: 39.472274, lng: -0.3557454,
    url: "https://morty.app/attraction/60986/la-tienda-de-te-dell-sr-miyagi",
    notes: "",
  },
  {
    id: "w61235",
    name: "Midnite",
    venue: "OuterGround Escape Rooms",
    city: "Rijswijk",
    state: "",
    country: "Netherlands",
    lat: 52.0407939, lng: 4.3329561,
    url: "https://morty.app/attraction/61235/midnite-midnight",
    notes: "",
  },
  {
    id: "w61537",
    name: "The Lakehouse",
    venue: "The Sanctuary Escape Games",
    city: "Oklahoma City",
    state: "OK",
    country: "United States",
    lat: 35.461513, lng: -97.6489058,
    url: "https://morty.app/attraction/61537/the-lakehouse",
    notes: "",
  },
  {
    id: "w61548",
    name: "EXTERMINATED: Terror at the Junkyard",
    venue: "Evasive Escape Rooms",
    city: "Sarasota",
    state: "FL",
    country: "United States",
    lat: 27.3371292, lng: -82.4698621,
    url: "https://morty.app/attraction/61548/exterminated-terror-at-the-junkyard",
    notes: "",
  },
  {
    id: "w61811",
    name: "Magic Universe",
    venue: "Mad Land",
    city: "Algete",
    state: "",
    country: "Spain",
    lat: 40.5950568, lng: -3.5444487,
    url: "https://morty.app/attraction/61811/magic-universe",
    notes: "",
  },
  {
    id: "w62010",
    name: "Ctrl Alt Reboot",
    venue: "Escaparium - Laval",
    city: "Laval",
    state: "",
    country: "Canada",
    lat: 45.5859362, lng: -73.768368,
    url: "https://morty.app/attraction/62010/ctrlaltdel-reboot",
    notes: "",
  },
  {
    id: "w62134",
    name: "Heist Havoc",
    venue: "Redacted Escape Rooms",
    city: "West Allis",
    state: "WI",
    country: "United States",
    lat: 42.9966162, lng: -88.0428949,
    url: "https://morty.app/attraction/62134/heist-havoc",
    notes: "",
  },
  {
    id: "w62496",
    name: "The Tears of Freya",
    venue: "Mystic Escape Room - Denver",
    city: "Denver",
    state: "CO",
    country: "United States",
    lat: 39.7306132, lng: -104.999079,
    url: "https://morty.app/attraction/62496/tears-of-freya",
    notes: "",
  },
  {
    id: "w62936",
    name: "Dragon's Quest",
    venue: "Escape Utah - Midvale [prev. Castle of Chaos]",
    city: "Midvale",
    state: "UT",
    country: "United States",
    lat: 40.6063688, lng: -111.891156,
    url: "https://morty.app/attraction/62936/dragons-quest",
    notes: "",
  },
  {
    id: "w62997",
    name: "Proyecto DCrisis [Project DCrisis]",
    venue: "Paradiso Escape Room",
    city: "Leganes",
    state: "",
    country: "Spain",
    lat: 40.3286567, lng: -3.7644195,
    url: "https://morty.app/attraction/62997/proyecto-dcrisis-project-dcrisis",
    notes: "",
  },
  {
    id: "w63147",
    name: "[异能觉醒]诺亚 [Powers Awakening: Noah]",
    venue: "X先生&屋有岛·沉浸密室体验馆(悠唐店) [Mr. X - Youtang Store]",
    city: "Beijing",
    state: "",
    country: "China",
    lat: 39.93504, lng: 116.44985,
    url: "https://morty.app/attraction/63147/yi-neng-jue-xing-nuo-ya-powers-awakening-noah",
    notes: "",
  },
  {
    id: "w63988",
    name: "Le Château du Supplice Éternel [The Castle of Eternal Suffering]",
    venue: "Sauve Qui Peut - Saint-Jean",
    city: "Saint-Jean-sur-Richelieu",
    state: "",
    country: "Canada",
    lat: 45.3048323, lng: -73.2509583,
    url: "https://morty.app/attraction/63988/le-chateau-du-supplice-eternel-the-castle-of-eternal-suffering",
    notes: "",
  },
  {
    id: "w64125",
    name: "Twisted Matrix",
    venue: "Maze Rooms - Vermont",
    city: "Los Angeles",
    state: "CA",
    country: "United States",
    lat: 34.0722247, lng: -118.2912705,
    url: "https://morty.app/attraction/64125/matrix",
    notes: "",
  },
  {
    id: "w64394",
    name: "Himitsu Station - The Forgotten Markets",
    venue: "Himitsu Station",
    city: "Salt Lake City",
    state: "UT",
    country: "United States",
    lat: 40.7631412, lng: -111.8944468,
    url: "https://morty.app/attraction/64394/himitsu-station-the-forgotten-markets",
    notes: "",
  },
  {
    id: "w64459",
    name: "Escape Boardom",
    venue: "Escape Boredom",
    city: "Clearfield",
    state: "UT",
    country: "United States",
    lat: 41.1031297, lng: -112.0111861,
    url: "https://morty.app/attraction/64459/escape-boardom",
    notes: "",
  },
  {
    id: "w64482",
    name: "Londium",
    venue: "Londium Escape Room",
    city: "Montcada i Reixac",
    state: "",
    country: "Spain",
    lat: 41.4952778, lng: 2.1806155,
    url: "https://morty.app/attraction/64482/londium",
    notes: "",
  },
  {
    id: "w64583",
    name: "Haunted Harbor",
    venue: "The Escape Ventures - Winter Garden [prev. Escape Goat]",
    city: "Winter Garden",
    state: "FL",
    country: "United States",
    lat: 28.5703993, lng: -81.5678425,
    url: "https://morty.app/attraction/64583/haunted-harbor",
    notes: "",
  },
  {
    id: "w64867",
    name: "Big Brain Labs",
    venue: "60Out - Hollywood",
    city: "Los Angeles",
    state: "CA",
    country: "United States",
    lat: 34.095432, lng: -118.309021,
    url: "https://morty.app/attraction/64867/big-brain-labs",
    notes: "",
  },
  {
    id: "w64911",
    name: "Motel Molly",
    venue: "Omescape - San Jose",
    city: "San Jose",
    state: "CA",
    country: "United States",
    lat: 37.3147229, lng: -121.8516703,
    url: "https://morty.app/attraction/64911/motel-molly",
    notes: "",
  },
  {
    id: "w65294",
    name: "The Nemesis",
    venue: "Mission Escape Games",
    city: "New York",
    state: "NY",
    country: "United States",
    lat: 40.7542064, lng: -73.9916615,
    url: "https://morty.app/attraction/65294/the-nemesis",
    notes: "",
  },
  {
    id: "w65748",
    name: "Odin's Dilemma",
    venue: "Escape Gallery",
    city: "Poulsbo",
    state: "WA",
    country: "United States",
    lat: 47.7432639, lng: -122.6394816,
    url: "https://morty.app/attraction/65748/odins-dilemma",
    notes: "",
  },
  {
    id: "w65771",
    name: "The Buried Prophecy",
    venue: "Quest Tavern - Upland",
    city: "Pomona",
    state: "CA",
    country: "United States",
    lat: 34.1081779, lng: -117.7477543,
    url: "https://morty.app/attraction/65771/the-buried-prophecy",
    notes: "",
  },
  {
    id: "w65971",
    name: "The Chopshop",
    venue: "RAGESCAPE Rage & Escape Rooms",
    city: "Oceanside",
    state: "CA",
    country: "United States",
    lat: 33.1943096, lng: -117.357171,
    url: "https://morty.app/attraction/65971/the-chopshop",
    notes: "",
  },
  {
    id: "w66035",
    name: "Arbreville",
    venue: "De Gouden Kooi",
    city: "Mechelen",
    state: "",
    country: "Belgium",
    lat: 51.0264232, lng: 4.4755305,
    url: "https://morty.app/attraction/66035/arbreville",
    notes: "",
  },
  {
    id: "w66040",
    name: "Puñalada [Stab]",
    venue: "Friki Escape Room",
    city: "Madrid",
    state: "",
    country: "Spain",
    lat: 40.3798206, lng: -3.6049626,
    url: "https://morty.app/attraction/66040/punalada-stab",
    notes: "",
  },
  {
    id: "w66380",
    name: "Neon Shadows: The Polybius Files",
    venue: "The Escape Artist - West Seattle",
    city: "Seattle",
    state: "WA",
    country: "United States",
    lat: 47.5623837, lng: -122.3873958,
    url: "https://morty.app/attraction/66380/polybius-lives",
    notes: "",
  },
  {
    id: "w66692",
    name: "Factory Heist: Operation Green Bean",
    venue: "Evasive Escape Rooms",
    city: "Sarasota",
    state: "FL",
    country: "United States",
    lat: 27.3371292, lng: -82.4698621,
    url: "https://morty.app/attraction/66692/factory-heist-operation-green-bean",
    notes: "",
  },
  {
    id: "w66731",
    name: "The Whispering Pages at Blackwood Library",
    venue: "Escape Reality ",
    city: "Sarasota",
    state: "FL",
    country: "United States",
    lat: 27.3867168, lng: -82.5028687,
    url: "https://morty.app/attraction/66731/the-whispering-pages-at-blackwood-library",
    notes: "",
  },
  {
    id: "w67898",
    name: "Sleep",
    venue: "Down the Hatch",
    city: "Voorburg",
    state: "",
    country: "Netherlands",
    lat: 52.0840536, lng: 4.3610855,
    url: "https://morty.app/attraction/67898/sleep",
    notes: "",
  },
];
